// <auto-generated />
namespace InvoiceManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _20220628_ready : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20220628_ready));
        
        string IMigrationMetadata.Id
        {
            get { return "202206281812192_20220628_ready"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
